package world.pasds.back.authority.entity;

public enum AuthorityName {
    PRIVATE_DATA_CREATE,
    PRIVATE_DATA_READ,
    PRIVATE_DATA_UPDATE,
    PRIVATE_DATA_DELETE,
    ROLE_CREATE,
    ROLE_READ,
    ROLE_UPDATE,
    ROLE_DELETE,
    TEAM_UPDATE,
    TEAM_DELETE,
    ORGANIZATION_INVITE,
    TEAM_INVITE,
    TEAM_REMOVE,
    CHANGE_ROLE
}
